DELETE FROM holdings WHERE place_id='wild-madriu-perafita-claror-valley-q332800';
DELETE FROM holdings WHERE place_id='wild-cultural-sites-of-al-ain-hafit-hili-bidaa-bint-sau-q3962347';
DELETE FROM holdings WHERE place_id='wild-historic-centres-of-berat-and-gjirokaster-q3664670';
DELETE FROM holdings WHERE place_id='wild-monastery-of-geghard-and-the-upper-azat-valley-q17155656';
DELETE FROM holdings WHERE place_id='wild-gobustan-state-historical-and-cultural-reserve-q318181';
DELETE FROM holdings WHERE place_id='wild-jesuit-missions-among-the-guarani-q465960';
DELETE FROM holdings WHERE place_id='wild-writing-on-stone-provincial-park-q8038519';
DELETE FROM holdings WHERE place_id='wild-la-chaux-de-fonds-le-locle-watchmaking-town-planni-q3207298';
DELETE FROM holdings WHERE place_id='wild-qingchengshan-dujiangyan-national-park-q14230458';
DELETE FROM holdings WHERE place_id='wild-silk-roads-the-routes-network-of-chang-an-tianshan-q17277933';
DELETE FROM holdings WHERE place_id='wild-lednice-valtice-cultural-landscape-q735278';
DELETE FROM holdings WHERE place_id='wild-romerkastell-halheim-q62069250';
DELETE FROM holdings WHERE place_id='wild-ancient-thebes-with-its-necropolis-q141298543';
DELETE FROM holdings WHERE place_id='wild-archaeological-ensemble-of-merida-q15233334';
DELETE FROM holdings WHERE place_id='wild-campus-de-alcala-de-henares-university-of-alcala-q127413732';
DELETE FROM holdings WHERE place_id='wild-historic-city-of-toledo-q17255635';
DELETE FROM holdings WHERE place_id='wild-old-city-of-salamanca-q12156631';
DELETE FROM holdings WHERE place_id='wild-old-town-of-segovia-and-its-aqueduct-q15728389';
DELETE FROM holdings WHERE place_id='wild-university-and-historic-precinct-of-alcala-de-hena-q47531644';
DELETE FROM holdings WHERE place_id='wild-old-town-of-caceres-q9757828';
DELETE FROM holdings WHERE place_id='wild-prehistoric-pile-dwellings-around-the-alps-q4580';
DELETE FROM holdings WHERE place_id='wild-stone-circles-of-senegambia-q98769058';
DELETE FROM holdings WHERE place_id='wild-historic-city-of-trogir-q17132483';
DELETE FROM holdings WHERE place_id='wild-historical-complex-of-split-with-the-palace-of-dio-q17132416';
DELETE FROM holdings WHERE place_id='wild-beit-she-arim-national-park-q830805';
DELETE FROM holdings WHERE place_id='wild-18th-century-royal-palace-at-caserta-with-the-park-q16962666';
DELETE FROM holdings WHERE place_id='wild-genoa-le-strade-nuove-and-the-system-of-the-palazz-q10293286';
DELETE FROM holdings WHERE place_id='wild-historic-villages-of-korea-hahoe-and-yangdong-q3113345';
DELETE FROM holdings WHERE place_id='wild-cultural-reserve-of-kernave-q12676460';
DELETE FROM holdings WHERE place_id='wild-natural-and-culturo-historical-region-of-kotor-q3511938';
DELETE FROM holdings WHERE place_id='wild-historical-monuments-at-makli-thatta-q10332177';
DELETE FROM holdings WHERE place_id='wild-landscape-of-the-pico-island-vineyard-culture-q2448665';
DELETE FROM holdings WHERE place_id='wild-kapova-cave-q1643788';
DELETE FROM holdings WHERE place_id='wild-solovetsky-islands-q205711';
DELETE FROM holdings WHERE place_id='wild-solovetsky-state-museum-reserve-q18785988';
DELETE FROM holdings WHERE place_id='wild-saloum-delta-q559363';
DELETE FROM holdings WHERE place_id='wild-ayutthaya-historical-park-q1025100';
DELETE FROM holdings WHERE place_id='wild-historic-town-of-sukhothai-and-associated-historic-q865097';
DELETE FROM holdings WHERE place_id='wild-kyiv-saint-sophia-cathedral-and-related-monastic-b-q16363487';
DELETE FROM holdings WHERE place_id='wild-cahokia-q333661';
DELETE FROM holdings WHERE place_id='wild-poverty-point-q964745';
DELETE FROM holdings WHERE place_id='wild-samarkand-crossroad-of-cultures-q17255582';
DELETE FROM places WHERE id='wild-madriu-perafita-claror-valley-q332800' AND type='sanctuary';
DELETE FROM places WHERE id='wild-cultural-sites-of-al-ain-hafit-hili-bidaa-bint-sau-q3962347' AND type='sanctuary';
DELETE FROM places WHERE id='wild-historic-centres-of-berat-and-gjirokaster-q3664670' AND type='sanctuary';
DELETE FROM places WHERE id='wild-monastery-of-geghard-and-the-upper-azat-valley-q17155656' AND type='sanctuary';
DELETE FROM places WHERE id='wild-gobustan-state-historical-and-cultural-reserve-q318181' AND type='sanctuary';
DELETE FROM places WHERE id='wild-jesuit-missions-among-the-guarani-q465960' AND type='sanctuary';
DELETE FROM places WHERE id='wild-writing-on-stone-provincial-park-q8038519' AND type='sanctuary';
DELETE FROM places WHERE id='wild-la-chaux-de-fonds-le-locle-watchmaking-town-planni-q3207298' AND type='sanctuary';
DELETE FROM places WHERE id='wild-qingchengshan-dujiangyan-national-park-q14230458' AND type='sanctuary';
DELETE FROM places WHERE id='wild-silk-roads-the-routes-network-of-chang-an-tianshan-q17277933' AND type='sanctuary';
DELETE FROM places WHERE id='wild-lednice-valtice-cultural-landscape-q735278' AND type='sanctuary';
DELETE FROM places WHERE id='wild-romerkastell-halheim-q62069250' AND type='sanctuary';
DELETE FROM places WHERE id='wild-ancient-thebes-with-its-necropolis-q141298543' AND type='sanctuary';
DELETE FROM places WHERE id='wild-archaeological-ensemble-of-merida-q15233334' AND type='sanctuary';
DELETE FROM places WHERE id='wild-campus-de-alcala-de-henares-university-of-alcala-q127413732' AND type='sanctuary';
DELETE FROM places WHERE id='wild-historic-city-of-toledo-q17255635' AND type='sanctuary';
DELETE FROM places WHERE id='wild-old-city-of-salamanca-q12156631' AND type='sanctuary';
DELETE FROM places WHERE id='wild-old-town-of-segovia-and-its-aqueduct-q15728389' AND type='sanctuary';
DELETE FROM places WHERE id='wild-university-and-historic-precinct-of-alcala-de-hena-q47531644' AND type='sanctuary';
DELETE FROM places WHERE id='wild-old-town-of-caceres-q9757828' AND type='sanctuary';
DELETE FROM places WHERE id='wild-prehistoric-pile-dwellings-around-the-alps-q4580' AND type='sanctuary';
DELETE FROM places WHERE id='wild-stone-circles-of-senegambia-q98769058' AND type='sanctuary';
DELETE FROM places WHERE id='wild-historic-city-of-trogir-q17132483' AND type='sanctuary';
DELETE FROM places WHERE id='wild-historical-complex-of-split-with-the-palace-of-dio-q17132416' AND type='sanctuary';
DELETE FROM places WHERE id='wild-beit-she-arim-national-park-q830805' AND type='sanctuary';
DELETE FROM places WHERE id='wild-18th-century-royal-palace-at-caserta-with-the-park-q16962666' AND type='sanctuary';
DELETE FROM places WHERE id='wild-genoa-le-strade-nuove-and-the-system-of-the-palazz-q10293286' AND type='sanctuary';
DELETE FROM places WHERE id='wild-historic-villages-of-korea-hahoe-and-yangdong-q3113345' AND type='sanctuary';
DELETE FROM places WHERE id='wild-cultural-reserve-of-kernave-q12676460' AND type='sanctuary';
DELETE FROM places WHERE id='wild-natural-and-culturo-historical-region-of-kotor-q3511938' AND type='sanctuary';
DELETE FROM places WHERE id='wild-historical-monuments-at-makli-thatta-q10332177' AND type='sanctuary';
DELETE FROM places WHERE id='wild-landscape-of-the-pico-island-vineyard-culture-q2448665' AND type='sanctuary';
DELETE FROM places WHERE id='wild-kapova-cave-q1643788' AND type='sanctuary';
DELETE FROM places WHERE id='wild-solovetsky-islands-q205711' AND type='sanctuary';
DELETE FROM places WHERE id='wild-solovetsky-state-museum-reserve-q18785988' AND type='sanctuary';
DELETE FROM places WHERE id='wild-saloum-delta-q559363' AND type='sanctuary';
DELETE FROM places WHERE id='wild-ayutthaya-historical-park-q1025100' AND type='sanctuary';
DELETE FROM places WHERE id='wild-historic-town-of-sukhothai-and-associated-historic-q865097' AND type='sanctuary';
DELETE FROM places WHERE id='wild-kyiv-saint-sophia-cathedral-and-related-monastic-b-q16363487' AND type='sanctuary';
DELETE FROM places WHERE id='wild-cahokia-q333661' AND type='sanctuary';
DELETE FROM places WHERE id='wild-poverty-point-q964745' AND type='sanctuary';
DELETE FROM places WHERE id='wild-samarkand-crossroad-of-cultures-q17255582' AND type='sanctuary';
