#!/usr/bin/env python3
"""Export Wild Atlas app animal content for the website's calendar "lite" pages.

The calendar gives every animal day whose animal is in a Wild Atlas pack its
own page, built from the app's existing (advisor-reviewed) English copy and
images instead of a bespoke article.

Reads (read-only) from the app repo:
  WildAtlas/Data/wild_atlas_catalog.json        packs, names, IUCN, sizes
  WildAtlas/Data/wild_atlas_strings.en.json     English copy (animal namespace)
  output/<id>_adult_action.png, <id>_infant.png, GeneratedHeroImages/<id>_hero.png,
  GeneratedMeasurementImages/scale/<id>_scale_composite.png

Writes:
  _data/appAnimals.json                  text + metadata for EVERY animal in a
                                         visible pack (hidden packs excluded)
  assets/animals/<id>/{cover,scale,baby}.jpg   images, only for the ids that the
                                         calendar needs (_data/animalDays.json
                                         entries with `appId`)

Deliberately NOT exported: danger/safety lines and jokes (written for the
in-app context), and anything from hidden packs (Mythical Menagerie).

Usage:  python3 scripts/export_app_animals.py [--app ../PetPeeper]
Requires: macOS `sips` for image conversion.
"""
import argparse, json, os, subprocess, sys

HIDDEN_TIERS = {"hidden"}
TEXT_KEYS = ["summary.young", "summary.tiny", "fun_facts.young", "fun_facts.tiny",
             "did_you_know.young", "size_comparison.young", "weight_comparison.young",
             "map_narration", "sound_description.young"]
IMAGES = {  # output name -> candidate sources (first that exists wins)
    "cover": ["output/{id}_adult_action.png", "GeneratedHeroImages/{id}_hero.png"],
    "scale": ["GeneratedMeasurementImages/scale/{id}_scale_composite.png"],
    "baby": ["output/{id}_infant.png"],
    "weight": ["GeneratedMeasurementImages/weight/{id}_weight.png"],
}

def main():
    here = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    ap = argparse.ArgumentParser()
    ap.add_argument("--app", default=os.path.join(here, "..", "PetPeeper"))
    args = ap.parse_args()
    app = os.path.abspath(args.app)
    catalog = json.load(open(os.path.join(app, "WildAtlas/Data/wild_atlas_catalog.json")))
    strings = json.load(open(os.path.join(app, "WildAtlas/Data/wild_atlas_strings.en.json")))["namespaces"]
    animal_str, pack_str = strings.get("animal", {}), strings.get("pack", {})

    out = {}
    for pack in catalog["packs"]:
        if pack.get("tier") in HIDDEN_TIERS:
            continue
        for a in pack["animals"]:
            aid = a["animal_id"]
            s = animal_str.get(aid, {})
            out[aid] = {
                "name": a.get("common_name"),
                "scientificName": a.get("scientific_name"),
                "pack": pack["pack_id"], "packName": pack.get("display_name"), "packTier": pack.get("tier"),
                "iucn": a.get("iucn"), "habitat": a.get("habitat"), "foundIn": a.get("found_in"),
                "weightKg": a.get("weight_kg"), "lengthM": a.get("length_m"), "heightM": a.get("shoulder_height_m"),
                "text": {k: s[k] for k in TEXT_KEYS if k in s},
            }

    days = json.load(open(os.path.join(here, "_data/animalDays.json")))
    needed = sorted({d["appId"] for d in days.get("days", []) + days.get("alsoCelebrated", []) if d.get("appId")})
    missing = [n for n in needed if n not in out]
    if missing:
        sys.exit(f"appId not in a visible pack: {missing}")

    for aid in needed:
        dest = os.path.join(here, "assets/animals", aid)
        os.makedirs(dest, exist_ok=True)
        imgs = {}
        for name, cands in IMAGES.items():
            src = next((os.path.join(app, c.format(id=aid)) for c in cands if os.path.exists(os.path.join(app, c.format(id=aid)))), None)
            if not src:
                continue
            target = os.path.join(dest, f"{name}.jpg")
            if not os.path.exists(target) or os.path.getmtime(target) < os.path.getmtime(src):
                subprocess.run(["sips", "-s", "format", "jpeg", "-s", "formatOptions", "68", "-Z", "900", src, "--out", target],
                               check=True, stdout=subprocess.DEVNULL)
            imgs[name] = f"/assets/animals/{aid}/{name}.jpg"
        out[aid]["images"] = imgs

    json.dump({"_note": "Generated by scripts/export_app_animals.py from the Wild Atlas app (read-only). Do not hand-edit.",
               "animals": out}, open(os.path.join(here, "_data/appAnimals.json"), "w"), indent=1, ensure_ascii=False)
    print(f"exported {len(out)} animals; images for {len(needed)}: {needed}")

if __name__ == "__main__":
    main()
